#! /usr/bin/env python

arch = Options.options.arch

if arch == 'i386':
	arch_source_dirs = 'i386 i386/debug i386/mm i386/pic i386/pm i386/vesa'
else:
	arch_source_dirs = ''
	
source_dirs			= '. mm pm ipc vfs iom pit rtc syscall ' + arch_source_dirs 
acpi_source_dirs	= 'acpi acpi/events acpi/hardware acpi/interpreter/dispatcher acpi/interpreter/executer acpi/interpreter/parser acpi/namespace acpi/resources acpi/tables acpi/utilities '

include_dirs		= '../include/'
acpi_include_dirs	= include_dirs + ' ../include/kernel/acpi/'

#build acpi
acpi = bld.new_task_gen('cc', 'staticlib', target='acpi', name='acpi', install_path=None, includes=acpi_include_dirs, uselib='ACPI')
acpi.find_sources_in_dirs(acpi_source_dirs)

# build kernel
kernel = bld.new_task_gen('cc', 'program', target='kernel', name='kernel', install_path=None, includes=include_dirs, uselib_local='acpi ds sync string heap', uselib='KERNEL')
kernel.env['program_PATTERN'] = '%s.sys'
kernel.find_sources_in_dirs(source_dirs)
