#	File			:	doc makefile
#   Author			:	Samuel Jacob
#  	Version			:	3.0
#  	Created 		:	11-Oct-2007
#	Last modified	:
#	Brief			:	commands supported are: all clean

all:
	doxygen Doxyfile
	
clean:
	rm -r -f doxygen_doc