/*!
  \file		kernel/pit/pit.c
  \brief	Defines the interface for all PIT-related functions
*/


#include <ace.h>
#include <kernel/time.h>
#include <kernel/pit.h>
#include <kernel/ioapic.h>

/*! Timer tick - relative to the last tick - used for tickless system*/
static volatile UINT32 timer_ticks;

/* Elapsed seconds since boot - used for time keeping*/
volatile UINT32 ElapsedSeconds = 0;

/*! This function is called for each timer tick generated by 8254.
*/
ISR_RETURN_CODE _8254Handler(INTERRUPT_INFO_PTR interrupt_info, void * arg)
{
	timer_ticks++;
	return ISR_END_PROCESSING;
}

/*! This function is called for each timer tick generated by the LAPIC timer.
*/
ISR_RETURN_CODE LapicTimerHandler(INTERRUPT_INFO_PTR interrupt_info, void * arg)
{
	timer_ticks++;
	return ISR_END_PROCESSING;
}

/*! Pauses the execution by the given number of milli seconds
 * \param ms - Miliseconds to pause
 */
void Delay(UINT32 ms)
{
	UINT32 ticks_to_go = timer_ticks + (ms / (1000/TIMER_FREQUENCY));
	while(timer_ticks < ticks_to_go);
}
