/*!
  \file		kernel/pit/pit.c
  \brief	Defines the interface for all PIT-related functions
*/


#include <ace.h>
#include <kernel/interrupt.h>
#include <kernel/time.h>
#include <kernel/ioapic.h>

extern void Init8254Timer(UINT32 frequency);

/*! Number of timer ticks elapsed since boot*/
static UINT32 timer_ticks;

/*! This function is called for each timer tick.
*/
ISR_RETURN_CODE TimerHandler (INTERRUPT_INFO_PTR interrupt_info, void * arg)
{
	timer_ticks++;
	return ISR_END_PROCESSING;
}

/*! Initializes a Programmable Interval Timer based on architecture
	\param frequency - number interrupts should be generated by the PIT
*/
int InitPit(UINT32 frequency)
{
	InstallInterruptHandler( legacy_irq_redirection_table[LEGACY_DEVICE_IRQ_TIMER] , TimerHandler, 0);
#if ARCH == i386
	Init8254Timer(frequency);
	return 0;
#endif
	return 1;
}

/*! Pauses execution by the given number of timer ticks
	\param ticks - Number of timer ticks to wait
*/
void TimerSleep(UINT32 ticks)
{
	UINT32 final_ticks; 

	final_ticks = timer_ticks + ticks;
	while(timer_ticks < final_ticks);
}

/*! Pauses the execution by the given number of milli seconds
 * \param ms - Miliseconds to pause
 */
void Delay(UINT32 ms)
{
	int i;
	for(i=0;i<(ms*1000);i++);
}

/*! returns number of timer ticks elapsed since boot*/
UINT32 ElapsedTicks()
{
	return timer_ticks;
}
