#!/usr/bin/env python

import os, Task, Options, Configure, Utils, misc

Configure.autoconfig = 1

VERSION				= '3.0.' + os.popen("svn info | grep Revision | cut -f2 -d:").read().strip()
APPNAME				= 'AceTools'
srcdir 				= '.'
blddir				= '../../toolsbuild'

debug_flags			= '-gdwarf-2 -g3'

c_flags				= '-Wall ' 

include_dirs 		= '../include/ /usr/include'

def configure(conf):
	conf.check_tool('gcc misc')
	conf.env.append_unique('CCFLAGS', c_flags )
	
	if Options.options.build_type == 'debug':
		conf.env.append_unique('CCFLAGS', debug_flags)  
		
def build(bld):
	mkmc = bld.new_task_gen('cc', 'program', source='mc/mkmc.c', target='mkmc', name='mkmc', includes=include_dirs, install_path=None,  includes=include_dirs, )

def set_options(opt):
	opt.add_option("--build", action="store", default="debug", help="Build type - release, debug", dest="build_type")
